;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Stat.Attack",NewTagName="Stat.AttackPower")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Passive.SpawnOrb",DevComment="")
+GameplayTagList=(Tag="Event.Kill",DevComment="")
+GameplayTagList=(Tag="Stat.AttackPower",DevComment="")
+GameplayTagList=(Tag="Stat.AttackSpeed",DevComment="")
+GameplayTagList=(Tag="Stat.Critical",DevComment="")
+GameplayTagList=(Tag="Stat.CriticalDamage",DevComment="")
+GameplayTagList=(Tag="Stat.Hp",DevComment="")
+GameplayTagList=(Tag="Stat.Speed",DevComment="")

